export const types = {
    REQUEST_LOGIN: "REQUEST_LOGIN",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAIL: "LOGIN_FAIL",
    REQUEST_JOURNAL_DATA: "REQUEST_JOURNAL_DATA",
    JOURNAL_DATA_SUCCESS: "JOURNAL_DATA_SUCCESS",
    JOURNAL_DATA_FAIL: "JOURNAL_DATA_FAIL"
}